---
version: '2.1'

services:
  #---------------------------------------------------------------------------#
  # Zookeeper Cluster                                                         #
  #---------------------------------------------------------------------------#
  zookeeper:
    image: confluentinc/cp-zookeeper:${KAFKA_CONFLUENT_VERSION}
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888

  #---------------------------------------------------------------------------#
  # Kafka Cluster                                                             #
  #---------------------------------------------------------------------------#
  kafka-1:
    image: confluentinc/cp-kafka:${KAFKA_CONFLUENT_VERSION}
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_COMPRESSION_TYPE: lz4
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_TRANSITION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSITION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1

  #---------------------------------------------------------------------------#
  # Schema Registry                                                           #
  #---------------------------------------------------------------------------#
  schema-registry:
    image: confluentinc/cp-schema-registry:${KAFKA_CONFLUENT_VERSION}
    depends_on:
      - kafka-1
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-1:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-1
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1

  #---------------------------------------------------------------------------#
  # REST proxy                                                                #
  #---------------------------------------------------------------------------#
  rest-proxy:
    image: confluentinc/cp-kafka-rest:${KAFKA_CONFLUENT_VERSION}
    depends_on:
      - kafka-1
      - schema-registry
    ports:
      - "127.0.0.1:8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-1:9092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_REST_CLIENT_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_REST_COMPRESSION_TYPE: lz4
      KAFKA_REST_LOG4J_LOGGERS: "io.confluent.kafka.serializers=WARN"

  #---------------------------------------------------------------------------#
  # Management Portal                                                         #
  #---------------------------------------------------------------------------#
  managementportal-app:
    image: radarbase/management-portal:2.0.0
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MANAGEMENTPORTAL_FRONTEND_CLIENT_SECRET: ""
      MANAGEMENTPORTAL_COMMON_BASE_URL: http://localhost:8080
      MANAGEMENTPORTAL_COMMON_MANAGEMENT_PORTAL_BASE_URL: http://localhost:8080
      MANAGEMENTPORTAL_OAUTH_CLIENTS_FILE: /mp-includes/config/oauth_client_details.csv
      MANAGEMENTPORTAL_CATALOGUE_SERVER_ENABLE_AUTO_IMPORT: 'false'
      JAVA_OPTS: -Xmx256m  # maximum heap size for the JVM running ManagementPortal, increase this as necessary
    volumes:
      - ./etc/:/mp-includes/

  gateway:
    build:
      context: ../../..
    image: radarbase/radar-gateway:${RADAR_GATEWAY_TAG}
    depends_on:
      - kafka-1
      - schema-registry
      - managementportal-app
    ports:
      - "127.0.0.1:8092:8092"
    command:
      - sh
      - -c
      - "sleep 30; exec radar-gateway"
    volumes:
      - ./etc/gateway.yml:/etc/radar-gateway/gateway.yml
