name: Snyk test
on:
  pull_request:
    branches:
      - master
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master

    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run Snyk to check for vulnerabilities
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: >
        snyk test
        --severity-threshold=high
        --configuration-matching='^runtimeClasspath$'
        --fail-on=upgradable
        --org=radar-base
